name = "tech-news-bot"
main = "index.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "tech-news-agent"
database_id = "035380d3-8f16-4e59-8b2f-1f6cd0107316"